apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: dataproc-flask-api
spec:
  hosts:
    - "*"
  gateways:
    - demo-6231-gateway   
  http:
    - match:
        - uri:
            prefix: /create
        - uri:
            prefix: /spark
        - uri:
            prefix: /results
        - uri:
            prefix: /health
      route:
        - destination:
            host: dataproc-flask-api
            subset: v1
          weight: 50
        - destination:
            host: dataproc-flask-api
            subset: v2
          weight: 50
        - destination:
            host: dataproc-flask-api
            subset: v3
          weight: 0

