apiVersion: v1
kind: Service
metadata:
  name: dataproc-flask-api
  labels:
    app: dataproc-flask-api
spec:
  type: ClusterIP
  selector:
    app: dataproc-flask-api
  ports:
    - name: http
      port: 5001
      targetPort: 5001
